#!/bin/bash

# Setup eno2 with DHCP
ip link set eno2 up
dhclient eno2

# Enable Jumo Frames OVN
ip link set ovs-system mtu 9000
ip link set br-int mtu 9000

# Setup 802.3ad bond connection
ip link add mlnx-bond type bond
ip link set mlnx-bond type bond miimon 100 mode 4
ip link set enp175s0 mtu 9000
ip link set enp175s0d1 mtu 9000
ip link set mlnx-bond mtu 9000
ip link set enp175s0 down
ip link set enp175s0d1 down
ip link set enp175s0 master mlnx-bond
ip link set enp175s0d1 master mlnx-bond
ip link set mlnx-bond up

# Setup RDMA network
ip link add link mlnx-bond name rdma-mgmt type vlan id 20
ip addr add 10.20.10.3/24 brd + dev rdma-mgmt
ip link set rdma-mgmt mtu 9000
ip link set rdma-mgmt up

# Setup OVS MGMT
ip link add link mlnx-bond name ovs-mgmt type vlan id 30
ip addr add 10.30.10.3/24 brd + dev ovs-mgmt
ip link set ovs-mgmt mtu 9000
ip link set ovs-mgmt up

# Setup INCUS MGMT
ip link add link mlnx-bond name incus-mgmt type vlan id 40
ip addr add 10.40.10.3/24 brd + dev incus-mgmt
ip link set incus-mgmt mtu 9000
ip link set incus-mgmt up

# Setup bdebruhl network
ip link add link mlnx-bond name bdebruhl type vlan id 50
ip link set bdebruhl mtu 9000
ip link set bdebruhl up

# Setup bhartma network
ip link add link mlnx-bond name bhartma type vlan id 60
ip link set bhartma mtu 9000
ip link set bhartma up

# Setup phoenix network
ip link add link mlnx-bond name phoenix type vlan id 70
ip link set phoenix mtu 9000
ip link set phoenix up

# Setup student-labs network
ip link add link mlnx-bond name student-labs type vlan id 100
ip link set student-labs mtu 9000
ip link set student-labs up

# Setup admin-labs network
ip link add link mlnx-bond name admin-labs type vlan id 200
ip link set admin-labs mtu 9000
ip link set admin-labs up
